#!/usr/bin/env bash

# install docker
# --------------------
# add docker's official gpg key:
sudo apt-get update
sudo apt-get install ca-certificates curl -y
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# add the repository to apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

if [ ! $(getent group docker) ]; then
  sudo groupadd docker
fi

sudo usermod -aG docker $USER

# create local bin
# --------------------
mkdir -p ~/.local/bin

# install utilities
# --------------------
sudo apt install tree bat stow tmux build-essential -y

# create soft-links to local bin
ln -s /usr/bin/batcat ~/.local/bin/bat

# soft link config
# stow -t ~ .
