#!/usr/bin/env bash

for cmd in fd fzf; do
    command -v "$cmd" >/dev/null || { echo "$cmd is required but not installed" >&2; exit 1; }
done

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(fd -HLt d \
                  --format '~/{//}' \
                  --base-directory "$HOME" \
                  --search-path 'repos' \
                  '^.git$' \
                  | fzf --tmux)
fi

[[ -z $selected ]] && exit 0

selected=${selected/#\~/${HOME}}
selected_name=${selected##*/}
selected_name=${selected_name//./-}
tmux_running=$(pgrep tmux)

if [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t=$selected_name
else
    tmux switch-client -t $selected_name
fi

