#!/usr/bin/env bash

command -v fd >/dev/null 2>&1 || { echo 'fd is required but not installed' >&2; exit 1; }
command -v fzf >/dev/null 2>&1 || { echo 'fd is required but not installed' >&2; exit 1; }

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(fd -HLt d \
                  --format '~/{//}' \
                  --base-directory "$HOME" \
                  --search-path 'repos' \
                  '^.git$' \
                  | fzf --tmux)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected=${selected/#\~/${HOME}}
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t=$selected_name
else
    tmux switch-client -t $selected_name
fi

