#!/bin/sh

for cmd in fd fzf; do
    command -v "$cmd" >/dev/null 2>&1 || {
        echo "'$cmd' is required but not installed" >&2
        exit 1
    }
done

if [ "$#" -gt 1 ]; then
    echo "creation of multiple sessions is not implemented yet" >&2
    exit 1
fi

if [ "$#" -eq 1 ]; then
    target="$1"
else
    target=$(
        fd -HLd 5 -t d \
            --format "~/{//}" \
            --base-directory "$HOME" \
            --search-path "repos" \
            "^\.git/?$" \
        | fzf --tmux | sed "s|^~|$HOME|")
fi

[ -z "$target" ] && exit 0

normalized_path=$(cd -P "$target" 2>/dev/null && pwd)

if [ -z "$normalized_path" ]; then
    echo "invalid path: $target" >&2
    exit 1
fi

base=$(basename "$normalized_path" | sed "s/\./-/g")

if ! tmux has-session -t=$base 2>/dev/null; then
    tmux new-session -dn 'shell' -s $base -c $normalized_path
fi

if [[ -z $TMUX ]]; then
    tmux attach -t=$base
else
    tmux switch-client -t $base
fi

